# Generated by Django 4.2.3 on 2023-08-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0003_mailingsettings_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], max_length=20, verbose_name='статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailer.client', verbose_name='адрес клиента')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailer.message', verbose_name='адрес клиента')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
