# Generated by Django 4.2.3 on 2023-08-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0004_mailinglog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='time',
            field=models.TimeField(verbose_name='время рассылки'),
        ),
    ]
