# Generated by Django 4.2.3 on 2023-08-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0005_alter_mailingsettings_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='client',
            name='mailing_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emailer.mailingsettings', verbose_name='рассылка'),
        ),
    ]
