# Generated by Django 4.2.3 on 2023-08-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0006_remove_client_mailing_list_client_mailing_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='client',
            name='mailing_list',
            field=models.ManyToManyField(blank=True, null=True, to='emailer.mailingsettings', verbose_name='рассылка'),
        ),
    ]
