# Generated by Django 4.2.3 on 2023-08-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0008_alter_mailinglog_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailer.mailingsettings', verbose_name='подписка клиента'),
        ),
    ]
