# Generated by Django 4.2.3 on 2023-08-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0010_client_user_mailingsettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mailing_list',
            field=models.ManyToManyField(to='emailer.mailingsettings', verbose_name='рассылка'),
        ),
    ]
